### ISSUE TITLE
Make not following inheritance chain to the delegated interface of abstract extended by concrete

### ISSUE THREAD

**Issue by GRMule** [rdlowrey/Auryn#100]
I don't like the title, but that was my 3rd try, so we'll go with it.

I have an interface, with an abstract class that implements the interface. Elsewhere, there is a concrete class which extends the abstract.

If I establish a delegate for the interface, then try to provision the concrete, make() will not call that delegate, but instead directly attempt to provision the concrete class.

````php
	include('../vendor/autoload.php');
	$injector = new Auryn\Injector();

	// given an interface
	interface iFoo {}
	// with an abstract implementation
	abstract class Foo implements iFoo {
		public function __construct(
			$argumentFactoryWouldProvide
		) {
		}
		abstract public function someMethod();
	}

	// and a concrete implementation
	class Bar extends Foo {
		public function someMethod() {}
	}

	// this factory can make any iFoo's
	class iFooFactory {
		public function makeMe() {
			return new Bar('factory-provided-argument');
		}
	}

	//$injector->alias('iFoo', 'Foo'); // this (and variations thereof) doesn't make a difference
	$injector->delegate('iFoo', 'iFooFactory::makeMe');

	$bar = $injector->make('Bar'); // expected: talk to my iFooFactory
						 // actual: exception about non-class Foo param
	var_dump($bar); // nope
````

**Comment by morrisonlevi** [comment]
The issue here is that the inject doesn't know that `Bar` is made from the `iFooFactory`; it only knows that `iFoo` is. Just because it is a subtype doesn't mean it will automatically inherit the delegation rules. Perhaps wait for feedback from @Danack or @rdlowrey to verify this, but I think this is working as intended.

**Comment by GRMule** [comment]
I figured as much. In my actual implementation, I am not directly calling make() for Bar as the repro above; it is a typehint of yet another class. When Auryn tries to provision that class, I run in to the same problem the code above has.

**Comment by GRMule** [comment]
I could see this as being the intended functionality, but I could also see it from the other angle (the one  I had hoped would work) -- make follows the inheritance chain and checks for delegates all the way up, and if it doesn't find anything THEN it tries direct provisioning.

**Comment by Danack** [comment]
As Levi said, the injector just doesn't know that Bar should be made when an instance of the interface is needed.

For your example, this can be solved either by telling Auryn to make Bar wherever an iFoo is needed.
```
    $injector->alias('iFoo', 'Bar');
    $injector->delegate('Bar', 'BarFactory::makeMe');
    $bar = $injector->make('Bar');
```

Or just to tell it to call the delegate directly wherever an iFoo is needed.
```
    $injector->delegate('iFoo', 'iFooFactory::makeMe');
    $bar = $injector->make('iFoo');
```

It is possible that your actual problem is more like #35 - which I might have a cunning idea for.

**Comment by GRMule** [comment]
In the actual use-case, there are many concrete objects like Bar, so I couldn't alias iFoo to one of them  -- the factory was going to deal with that. Other objects ask for these concrete objects by name, so I'm never actually using make() to get the Bar, it is a typehinted constructor parameter on a different object that I'm make()'ing. I figured delegating that to a factory would be easier than trying to get Auryn to figure it out.

I guess I'm after a "super delegate", one ring to bind them all. "ancestor delegate"? "curmudgeon"? Eh. Maybe I need to refactor.

**Comment by GRMule** [comment]
I didn't get into this with the first bit of code, just so it was more clear, but this is exactly what I'm trying to do. Not to drop an A-B problem or a SO question, just clarifying.

````php
    include('../vendor/autoload.php');
    $injector = new Auryn\Injector();

    interface iFoo {}
    abstract class Foo implements iFoo {
        public function __construct(
            $argumentFactoryWouldProvide
        ) {
        }
        abstract public function someMethod();
    }

    // and a concrete implementations
    class Bar extends Foo {
        public function someMethod() {}
    }
    class BarStool extends Foo {
        public function someMethod() {}
    }
    class CueBall extends Foo {
        public function someMethod() {}
    }

    // this factory can make any iFoo's
    class iFooFactory {
        public function makeMe($whichOne) {
            return new $whichOne('factory-provided-argument');
        }
    }
    class Fez {
        public function __construct(Bar, BarStool) {}
    }

    $injector->delegate('iFoo', 'iFooFactory::makeMe'); // expected to do jQuery

    $fez = $injector->make('Fez');
    var_dump($fez); // nope
````

**Comment by garrettw** [comment]
Not sure if this helps any, but I can tell you how Dice would handle this by default: when you make the new Fez object, it would look for any rules (like this delegation) that exactly match the class name, and if none are found, it looks for rules that match a class higher up the inheritance chain if possible.

**Comment by Danack** [comment]
> when you make the new Fez object, it would look for any rules (like this delegation) that exactly match the class name, and if none are found, it looks for rules that match a class higher up the inheritance chain if possible.

On the face of it, that doesn't sound like it would be compatible with how Auryn works internally - at least in one aspect.

```
class Bar implements Foo {}
class Baz implements Foo {}

$injector->share('Foo');
$injector->delegate('Foo', 'createFoo');
$injector->make('Bar'); 
$injector->make('Baz');

```

If the hierarchy was followed and it decided to make a 'Bar' for the first call to make, there would then have to be extra logic in place to prevent 'Bar' from being used when the call to make('Baz') was made.

@GRMule if you want to make this a real feature request, could you give a real example of how it would be useful, and why it wouldn't be better just to be explicit about the delegation?

**Comment by garrettw** [comment]
Following my line of logic, the only thing you should have to do for it to call createFoo() separately for each make() is remove the call to share().

**Comment by GRMule** [comment]
That's what I'm going to try myself, @garrettw, as I was making the Foo/Bar/Fez example, it occurred to me that it might work, rather than delegating the interface, delegate the abstract. @Danack I don't think it is a feature request. I was talking to rdlowry about it, and from the little I told him he wasn't sure if I had a bug or was doingitwrong. It seems that it is the latter.
