### ISSUE TITLE
Soft / optional dependencies

### ISSUE THREAD

**Issue by mattsah** [rdlowrey/auryn#109]
Forgive me if this has been asked before, and I know there's a way to specify them, but I'm trying to address the more "automatic" behavior as much as possible with this question.

As it stands, and as far as I can tell, Auryn will not try to instantiate dependencies which are typehinted, but which have been made optional, i.e it would not provide `__construct(Foo $foo = NULL)` with an instance of `Foo`.

It is possible to call make and directly say `':foo' => new $foo`, use a factory, etc... but I'm wondering if there's a particular reason that the default behavior is not really the opposite, i.e. unless explicitly told to give it `NULL`, try to construct those dependencies.

I realize these are not "dependencies" in a proper sense, as being optional implies the code is not dependent on them, but that they might provide some additional benefit (like a caching class that, when passed might make things faster), vs. if not passed everything is regenerated all the time.

That said, if my caching class can be built and passed automatically, why wouldn't I care to have it?

**Comment by mattsah** [comment]
I should add, in the particular case that I have, I actually have a concrete dependency registered for an interface, which is optional.  So I've gone through the trouble to say this interface is provided by this class, but then Auryn sees that the parameter is optional and doesn't bother to even try.

**Comment by rdlowrey** [comment]
I don't really feel strongly one way or another but the current behavior does seem a bit strange. This is something that can be classified as a "bug" and fixed if no one else raises objections.

**Comment by rdlowrey** [comment]
The fix for this issue can be found in the above linked branch. Pending further discussion it can be merged into master.

**Comment by Danack** [comment]
This was fixed by #101 wasn't it?

**Comment by mattsah** [comment]
If it was fixed already, I do apologize, I did a quick search and didn't find anything, and I might be locked on a prior stable version.  Although that would beg the question, what's the difference?  The newer one seems less restrictive (i.e. doesn't require the dependency to be set up otherwise, first)?

**Comment by Danack** [comment]
The rule that is implemented is meant to be:
* if the dependency is explicitly set up through an alias, delegation or sharing, then the injector will make the required type and pass it into the function.
* if the dependency is not explicitly setup, then the default value will be used.

i.e. if you told the injector how to make something, then it will use that instruction how to make something. If you didn't, it won't.

**Comment by rdlowrey** [comment]
So ... do we think the associated branch should be merged or not? I think both sides of the coin are sensible and I don't really have much preference between the two.

**Comment by vlakarados** [comment]
I'd like to vote for the @Danack's version. If you look at this from the creator's point of view of the class that dependencies are being injected to, everyone writes defaults like *"you can pass me something and I will use it, if you don't, it's no problem"*. So basically you'll loose the class's own implementation. If there is a default value, it's there for a reason.

**Comment by Danack** [comment]
@rdlowrey I think the current functionality in master is correct, and produces the desired behaviour for the example code below. The current behaviour is covered in [these tests](https://github.com/rdlowrey/auryn/blob/master/test/InjectorTest.php#L699-L732)

>  do we think the associated branch should be merged or not?

Nope, I think it gives the undesired behaviour of throwing an exception for the code below.

aka if @mattsah upgrades to the latest version, I believe Auryn will already be doing what they want.

```
class Bar implements BarInterface {

}

class Foo {
    function __construct(BarInterface $bar = null ) {
        $this->bar = $bar;
    }
}


$injector = new Auryn\Injector();
$bar = new Bar();
$injector->alias('BarInterface', get_class($bar));
$injector->share($bar);
$foo = $injector->make('Foo');
var_dump($foo);

$injector = new Auryn\Injector();
$foo = $injector->make('Foo');
var_dump($foo);

    
```

**Comment by rdlowrey** [comment]
Fine with me. Marking as "won't fix" for now. Thanks all for the input :+1:
