### ISSUE TITLE
Injecting dependencies to PDO returned entities.

### ISSUE THREAD

**Issue by vlakarados** [rdlowrey/auryn#112]
Would like to know if it's possible to inject dependencies to objects created by PDO `fetch/All(PDO::FETCH_CLASS, 'MyClass')`. Maybe someone already uses some workaround or found a way to do it properly? As `fetchAll()` doesn't allow `PDO::FETCH_INTO` style.

Currently I simply create arrays and pass them to class constructors along with the dependencies.
Looking into doing it with `PDO::FETCH_FUNC`. So what do you use?

**Comment by rdlowrey** [comment]
Well ... objects returned from the PDO fetch method are often intended to be value objects -- they shouldn't really have behavior. I don't see an issue with passing the "dumb" value object returned from the pdo fetch call into another class. But `PDO::FETCH_FUNC` should be fine if you want to do this.

**Comment by vlakarados** [comment]
Sometimes it's really helpful to have moments of ORM to quickly get a relationship from an entity (I tend to think Auryn doesn't try to limit it's users or to force them to anything). `$post->getCommentsCount();` is something that might be useful, that might require something like a repository dependency. I understand it's not actually a dependency in this case, but it's only a simple example from the top of my head.

What might be the other ways to do this besides `FETCH_FUNC`?

**Comment by Danack** [comment]
> What might be the other ways to do this besides FETCH_FUNC?

It sounds like you might want to check out the Zend/Doctrine object hydration libraries....however they are way out of scope for a DI library.

**Comment by vlakarados** [comment]
@Danack, I'm familiar with them, but that's why I want to use Auryn+PDO, PDO takes care of object hydration, while Auryn (what I'm currently looking for) will take care on dependencies entity depndency and thus, behavior. Or do you mean something else?
Basically as I see it: PDO delegates object creation to Auryn, when it's created and `__construct()` has been invoked, PDO hydrates object properties. Probably this method will also allow easy mutation of properties.

Anyway, I will try to implement this and share some codes so maybe someone will improve it or find a better way.

**Comment by kelunik** [comment]
@vlakarados Can I close this one?

**Comment by vlakarados** [comment]
Sure, I think someday I'll come up to a solution and post it.
