### ISSUE TITLE
Sharing classes with annotations.

### ISSUE THREAD

**Issue by vlakarados** [rdlowrey/auryn#123]
When you start a new project, Auryn is one of the first things (in my case almost always the first) that get implemented, so when implementing all the business logic, you already think about what to share (dependencies) and what not.

Just like writing a singleton class, the checks for existing instance of the class is the responsibility of the class itself, so I think it would be right to make shared classes know they're shared by annotating themselves as shared, something like.

```
/** @Shared */
class MyClass
{
     // ...
}
```

Or `// AurynShared`, or something else, I won't say which one would fit better.

Seems pretty logical to have the dependency know if it should be shared.

This has it's advantage of being portable, in example, when making a public package, marked factory classes would already be shared for users who implement Auryn.

If this is implemented, and packages start to implement this annotation, we sometimes may require to explicitly 'unshare' the dependency, that is, override the annotation like `$injector->forceUnshared('MyClass');` or simply `->unshare()`.

Would like to hear your thoughts.

**Comment by kelunik** [comment]
This would require parsing the comments and slowing down everything. Since most applications are short-lived on a per-request basis, I don't think that's a good idea.

**Comment by vlakarados** [comment]
I'm not sure if placing Auryn specific properties in the class would be ok, so I suggested annotations. With active caching it wouldn't hurt much?

**Comment by morrisonlevi** [comment]
My thoughts are that documentation comments should not dictate behavior.

**Comment by J7mbo** [comment]
Agreed - I can't find the issue but we already discussed placing a sort of 'standard' for something similar. Auryn is a foundation to build your awesome stuff on - many people won't want annotations. 

You can implement that yourself, same with AOP and reflection, but it's not for everyone.

**Comment by garrettw** [comment]
I would also disagree with annotations - but further, I don't think it would maintain separation of concerns to have a class know whether it is shared or not. I strongly feel that that responsibility lies with the DIC and should stay there.

**Comment by vlakarados** [comment]
If the reason of rejection is performance, then I'm ok with that.

As with @morrisonlevi & @J7mbo - this will not affect any of your code, you either use that, either not. Nothing more than an if condition to see if they're turned on.

How would you reuse 3rd party class instances without knowing they should and may be shared safely beforehand?

**Comment by kelunik** [comment]
I want to reject this for multiple reasons:

1. Performance
2. Your code shouldn't be aware of the injector
3. Comments should not dictate code behavior
