### ISSUE TITLE
delegate() had args removed. Why?

### ISSUE THREAD

**Issue by J7mbo** [rdlowrey/auryn#126]
Back in 0.14 I saw (and regularly used) the following signature for `delegate`: 

`public function delegate($className, $callable, array $args = array());`

Seems like [this commit](https://github.com/rdlowrey/auryn/commit/cde462db43d246f394ab3d8f8ba1af4bdcb8cc97#diff-fd6db98bf5b2663e93188de66b04b855R222) was responsible for removing the args. Why was the ability to pass in `$args` here removed? I used it regularly for Doctrine repositories and just realised - it's not bloody there any more!!

Alternative? Tried using `define` and failed. Please could we just put that back and not tell anyone? :-)

**Comment by Danack** [comment]
Sooo....ugh.

I had a look at implementing this, and while it's [technically possible](https://github.com/Danack/Auryn/commit/20b4d63405c829afda8b2000b45268fa787ffcd1) I don't think we should do it.

The short version is that all of the 'extraParams' that can be passed around to $injector->make(), $injector->execute() and now potentially `$injector->delegate()` clash with each other - and there are inherently edge-case where for one person they should be applied in one order, and for other people they should be applied in a different order.

This seems a bad piece of complexity to add. And the problem can be solved in user code sanely.

e.g. if before you had this:


```
function createRepo($name, EM $entityManager) {
    return $entityManager->create($name);
}

$injector->delegate('Bugs', 'createRepo', [':name' => 'Bugs'])
$injector->delegate('Users', 'createRepo', [':name' => 'Users'])
```

You could either refactor it to use 'just functions':

```
function createBugsRepo(EM $entityManager) {
    return $entityManager->create('Bugs');
}

function createUsersRepo(EM $entityManager) {
    return $entityManager->create('Users');
}

$injector->delegate('Bugs', 'createBugsRepo');
$injector->delegate('Users', 'createUsersRepo');
```


Or if you want to make it briefer, you could use closures like so:

```
function createRepoFn($name) {
    return function (EM $entityManager) use $name {
        return $entityManager->create($name);
    }
}

$injector->delegate('Bugs', createRepoFn('Bugs'));
$injector->delegate('Users', createRepoFn('Users'));

```

**Comment by kelunik** [comment]
Closing. If you still think we need this, please re-open.
