### ISSUE TITLE
Container inoperability implementation?

### ISSUE THREAD

**Issue by elazar** [rdlowrey/auryn#127]
I'm a developer of the [Spark ADR framework](https://github.com/sparkphp/spark), which uses Auryn. I recently learned about the [container-interopt standard](https://github.com/php-fig/fig-standards/blob/master/proposed/container.md). Since then, I've been considering if Auryn implementing this standard would make sense and, if so, what approach should be taken for such an implementation.

One notable point is that other container implementations typically used semantic names to reference individual dependencies, where Auryn instead references types (i.e. classes and interfaces).

It would be possible to support referencing dependencies by semantic name using a mapping of names to class/interface names, albeit by adding another level of indirection and a bit more runtime overhead. However, it would make Auryn more interoperable with other containers, and it could be added in new methods to maintain backward compatibility and allow users to avoid the overhead if it's unwanted.

At the code level, implementing the standard would likely just be a matter of having `Auryn\Injector` implement [this interface](https://github.com/container-interop/container-interop/blob/master/src/Interop/Container/ContainerInterface.php).

Implementing `ContainerInterface->get()` would be pretty straightforward: `Injector->get()` would handle resolving semantic names to corresponding class/interface names, then just call `Injector->make()` with the latter.

Implementing `ContainerInterface->has()` would be less straightforward. It seems like `Injector->make()` can theoretically resolve just about anything provided that 1) the class exists; and 2) it has no circular dependencies. I'm not sure of the best way to check the resolvability of something without actually instantiating it with `Injector->make()`. I'm open to suggestions on this particular point.

Thoughts?

**Comment by J7mbo** [comment]
Hey, we had a discussion on issue #77 on this. If you fancy making your own wrapper for it, that's easy enough, but it shouldn't become a part of Auryn.

**Comment by elazar** [comment]
@J7mbo Ah, fair enough. Apologies for the noise, thanks for the clarification.

**Comment by elazar** [comment]
In case anyone happens to come across this issue and the information is relevant to them, I have created a [container-interop wrapper for Auryn](https://github.com/elazar/auryn-container-interop).
