### ISSUE TITLE
[question] multiple shared instances of a class / multiple implementations of an interface

### ISSUE THREAD

**Issue by mdecaffmeyer** [rdlowrey/auryn#130]
How do you handle the cases where for example I have two shared PDO objects, with different configuration?
E.g. I'd have two databases and some classes need one instance and other classes would need the other one?
Seems like `$injector->share('PDO');` allows me to share only a single PDO instance.

In the same way, how do you handle interfaces with multiple implementations, where some classes need one of the implementation and other classes other implementations? Aliases seem to restrict to link an interface to a single concrete implementation class.
`$injector->alias('Engine', 'V8');` How about other classes that have an Engine dependency and I want to inject V6?

**Comment by kelunik** [comment]
How would you do it?

**Comment by vlakarados** [comment]
I'd simply create two extra classes that extend PDO and share them:

    class PGPDO extends PDO {}
    class MYPDO extends PDO {}

    $injector->share('DBOne');
    $injector->share('DBTwo');

And don't share `PDO`.

As to your interface question. If your classes *need* a specific implementation, you don't need an interface and should not alias at all.

**Comment by mdecaffmeyer** [comment]
@vlakarados that makes sense. However, what if I want to inject the PDO instances (PGPDO and MYPDO) to external classes that require a pdo instance typed hint as \PDO in their constructors?

**Comment by vlakarados** [comment]
Well, Auryn isn't magic, it doesn't and can't know which implementation you want if you don't specify it.

**Comment by mdecaffmeyer** [comment]
@vlakarados then it looks like for that case, I need to be able to tell Auryn, use *that* implementation of the interface (or super-class) for the class I want to instantiate (something global like the alias won't work for that case).
Again, for the case where I use an external class (of which I don't change the constructor's signature) that requires an interface (or super-class), and I have different implementations of it (e.g. PGPDO/MYPDO in the example you mentionned).

**Comment by morrisonlevi** [comment]
Another option is to configure the classes to use factories.

**Comment by vlakarados** [comment]
@mdecaffmeyer I think [this is something similar to what you're after](https://github.com/rdlowrey/auryn#defining-class-names-for-constructor-parameters). Define which implementation for which class you want. But honestly, I don't think it's the best way to achieve what you want. I'd stay with method from my first comment or used factories like @morrisonlevi mentioned.

**Comment by kelunik** [comment]
Auryn can't do magic. You either have to extend `PDO`, which is kind of ugly. Or share one instance and define the other one for each class that needs the other one.
