### ISSUE TITLE
v1.3.0 is broken

### ISSUE THREAD

**Issue by claudio-silva** [rdlowrey/auryn#140]
After updating from 1.2.0 to 1.3.0 my applications no longer work.
I get an 'undefined index' error at:
[lib/Injector.php, line 120](https://github.com/rdlowrey/auryn/commit/2fdd89dfbbb9a98de7361981df6d802a9a38e0a5#diff-fd6db98bf5b2663e93188de66b04b855R120)

Examining that line I can see something strange:
```php
$this->shares[$aliasNormalized] = $this->shares[$aliasNormalized];
```
The code is a no-op; the right side of the assignment is equal to the left side.

**Comment by rdlowrey** [comment]
Sorry about this. The offending code was reverted and a new 1.4 version was tagged here https://github.com/rdlowrey/auryn/commit/2e4240791162dfe073d59654d8dc06df0eb0b73f
