### ISSUE TITLE
Share instances by default

### ISSUE THREAD

**Issue by porebskk** [rdlowrey/auryn#142]
Hello,

I think a feature to make every instance being shared by default would be nice to have, as this would help projects which make heavy usage of stateless classes get rid of all the `share()` method calls.

**Comment by kelunik** [comment]
I think that's a bad idea, because it makes it impossible to have a instance which is not shared.

How does your bootstrapping currently look like?

**Comment by vlakarados** [comment]
I think @porebskk want's some global switch for injector instance which when set will make all future registered class instances shared by default.
Personally I think it's bad and Auryn will be abused as a ServiceLocator

**Comment by janoszen** [comment]
I agree that this should not happen. Having to share the things you make makes you think more about if you really need to share it.

If you need all instances shared by default, just write a simple wrapper around Auryn and make it happen there.

**Comment by badevilerror** [comment]
I'm not sure if i get why you say it shouldn't be possible in the injector.

For example, i'm composing a small web framework using different libs for my project, and to be honest in a framework there's a lot of things that _should_ be shared. In fact considering the whole request life-cycle in most web apps most things are shared by nature. All the services, controllers, repositories, listeners and what not. And for those cases that aren't you're probably better off to use a factory anyway (which in most cases is shared too).

Maybe i'm a little biased as i tend to make everything (except for entities and DTOs) stateless, and so i see no point in creating 10 instances of my `UserRepository` for every class that depends upon it.

Also abusing injector as a service locator is possible regardless of the proposed feature - i don't see why that would make it any worse. In fact there are many container implementations out there that suppose a single instance scope by default and make you tag it as prototype if you don't want it to be shared. I think it would be awesome if Auryn could be used both ways, depending on your needs.

Regarding writing a simple wrapper/facade around Auryn and handling it there - as proposed by janoszen - i'm not sure if that's possible. Of course you could wrap around `Injector::make()` but that's only an entry point and won't auto-share deeper/recursive dependencies. Only alternative would be to extend `Injector` class, which doesn't feel very elegant tbh. But maybe i'm missing something.

Anyway i would love to hear from you guys why do you exactly consider this as bad.

**Comment by Danack** [comment]
> Anyway i would love to hear from you guys why do you exactly consider this as bad.

Code should be safe by default, rather than 'going to explode' by default. Auryn can't tell if a class is stateless or not.

> Only alternative would be to extend Injector class, which doesn't feel very elegant tbh. 

Extending the injector class to make it behave exactly as you want is definitely the correct choice. There was a reasonable amount of work done to make this possible.

> Of course you could wrap around Injector::make()

You probably want to be wrapping around Injector::delegate() and injector::alias() to make them be Injector::delegateAndShare(), and Injector::aliasAndShare().

> In fact considering the whole request life-cycle in most web apps most 
> things are shared by nature. All the services, controllers, repositories, 
> listeners and what not.

I'd be reasonably interested to find out why those types of things are being created more than once, to the extent that it would cause a performance problem.

**Comment by badevilerror** [comment]
> Code should be safe by default, rather than 'going to explode' by default. Auryn can't tell if a class is stateless or not.

Agreed, although i'd agrue that would be programmer responsibility to make "unshared" all of the required objects - but i get your point and that's a valid one.

So if i'm not mistaken, all you say is that allowing to share _by default_ would be bad, and not the sole fact that 95% of objects in the application is shared?

If so my only complain would be, that in case of a bigger app you would end up with a really long list of classes to share. And this - obviously - could be hard to maintain.

> I'd be reasonably interested to find out why those types of things are being created more than once, to the extent that it would cause a performance problem.

So if i may ask, do you advice to just don't share and don't care about few more instances here and there (as long as there's only few of them, they're stateless and don't do any heavy stuff in the constructor it doesn't really matter) and care to share only those stateful or heavy to instantiate (like db connections etc)?

**Comment by Danack** [comment]
> do you advice to just don't share and don't care about few more instances here and there ...
> share only those stateful or heavy to instantiate (like db connections etc)?

Yes, I tend to only share those classes that have network connections, where sharing that class will give a performance boost, or where those classes need to have only one instance (e.g. zend-event-manager, amphp).

> that in case of a bigger app you would end up with a really long list of classes to share. 

Do you have an large app that you have seen this in? Or is this a future concern you have?

For me, this doesn't turn out to be a problem. Although each of the 'root' components that needs to be shared once is another line of code, the number of ways of combining these root dependencies grows factorially.

One 'factor' in this is that Auryn you can use other dependencies in delegate functions. This means that you combine those 'root' dependencies at the delegate layer.

$injector->delegate(Logger::class, 'createLogger');
$injector->delegate(\PDO::class, 'createLoggingPDO');

function createLogger() {
    // Creates a standard logger
}

function createLoggingPDO(Logger $logger) {
    // Creates an instance of PDO that is wrapped with logging functionality.
}

Setting up the shared instances is going to be one line of code per service that needs to be shared.....this is currently 10 for a non-trivial app, and would reach maybe 30 lines in a massive application.

If you do have a large app where this is a problem, I could give you an hour or so of consulting to perhaps suggest where you might be able to do things in a better way, or to at least see why it is a problem for you.
