### ISSUE TITLE
Resolve interfaces and abstracts to shared instances

### ISSUE THREAD

**Issue by Furgas** [rdlowrey/auryn#145]
Code in question:

``` php
interface A { }
class B implements A { }
class C {
    function __construct(A $a) { }
}

$b = new B();
$injector->share($b);

$injector->make(C::class);
```

Currently this code will fail with exception:
`Auryn\InjectionException: Injection definition required for interface A`

You must explicitly call following to get it working:

``` php
$injector->alias(A::class, get_class($b));
```

or

``` php
$injector->alias(A::class, B::class);
```

What do you think about adding automatic "last resort" resolving of interfaces and abstracts to shared instances? The simplest addition would be at `instantiateWithoutCtorParams` method:

``` php
...
        if (!$reflClass->isInstantiable()) {
            foreach ($this->shares as $sharedObject) {
                if ($sharedObject instanceof $className) {
                    return $sharedObject;
                }
            }
...
```

Probably it should throw exception when multiple shared objects can be used.

**Comment by kelunik** [comment]
What if you have two shared objects implementing that interface?

**Comment by Furgas** [comment]
@kelunik Look at the end of the post:)

**Comment by Danack** [comment]
> What do you think about adding automatic "last resort" resolving of interfaces and abstracts to shared instances? 

Honestly, it makes me very sad.

Boostrapping applications shouldn't be magic. Having classes be resolved implicitly just to skip defining the alias function adds a significant amount of implicit behaviour for the small benefit of having to write a line of config.

**Comment by J7mbo** [comment]
I'm on both sides. I'd love it as an *option* and there's plenty of 'magic' here anyway.

I can see how being explicit with your aliases is better, like @Danack says. Would this add overhead?

**Comment by kelunik** [comment]
This relates to #133.

**Comment by Danack** [comment]
I added some words in 6c06f163800693b712ae9c9bdd601d1c912356eb to explain why it was excluded.

[maybe direct link.](https://github.com/rdlowrey/auryn/blob/dev/excluded_features.md#resolve-interfaces-and-abstracts-to-shared-instances)
