### ISSUE TITLE
What is the correct way returning a "new View()" from controller when using auryn?

### ISSUE THREAD

**Issue by minutephp** [rdlowrey/auryn#146]
Hi,

I'm new to `auryn` and I'm still learning about IoC Dependency Injector. Anyway, please tell me if I understanding this correctly. Let's say I have a framework that executes a `Controller` class. The output of the controller is returned as new `View` class.

Hypothetical code:

```
Class SampleController {
    public function run() {
        return new View('content.html');
   }
}

Class View {
   public function __construct(string $template, Logger $logger) {
           $this->template = $template;
           $this->logger = $logger;
   }
}
```

Now as far as I can understand I should be using `$injector->make('View')` instead of `new View()` as the last statement in my controller. So does that mean I should be passing the `$injector` to all my controller functions when calling them like this:

Changed code:

```
Class SampleController {
    private $injector;

    public function __construct(Injector $injector) {
        $this->injector = $injector;
    }

    public function run() {
        $this->injector->make('View', ['content.html']);
   }
}
```

Is this the correct way of doing it or Is there some other way that is better? Thanks for helping me understand this.

**Comment by kelunik** [comment]
The correct thing would be to just return a `new View;`. If you need it, add a factory and inject it in the constructor of your controller. Your main code usually shouldn't be aware of Auryn at all.

**Comment by minutephp** [comment]
Hi,

Thanks for the reply. Since the `View` class requires access to `Logger`, and maybe other classes, it would be `new View('template_to_include', new Logger(new LogWriter()))`. 

But it looks confusing? Any advice on that?

**Comment by kelunik** [comment]
Does the view really need a logger? Shouldn't the controller already log everything needed?

You can inject the logger already into the controller:

```php
<?php

class Controller {
    private $logger;

    public function __construct(Logger $logger) {
        $this->logger = $logger;
    }

    // ...
}
```

As an alternative, you can have a `ViewFactory` that gets the logger injected on bootstrap by Auryn and injects it into the view then.

**Comment by minutephp** [comment]
Hi,

The `View` class requires template files and can also compile a few expressions, so the `Logger` is useful. In addition, I also want to learn the correct way of using `Auryn` since there may be other instances when I'm creating new classes that require recursive dependencies.

I'll try to find more information about `ViewFactory`. But IIRC is this supposed to be static method that returns a `new View()`? Because the docs says to stay away from static methods, singletons, and global variables. Or are you talking about something else?

Thanks for the help again.

**Comment by kelunik** [comment]
Factories being static methods aren't really helpful IMO. They should usually be normal objects, so you can replace them. If you use a static method / function, your code is coupled to that implementation. If you use an object with methods, you can replace the factory and make it return another instance, if you ever want to replace the `View` class.

```php
<?php

class Controller {
    private $viewFactory;

    public function __construct(ViewFactory $viewFactory) {
        $this->viewFactory = $viewFactory;
    }

    public function run() {
        return $this->viewFactory->create('View', ['content.html']);
    }
}

interface ViewFactory {
    public function create(string $name, array $data);
}

class DefaultViewFactory implements ViewFactory {
    // ...
}
```

**Comment by minutephp** [comment]
Yes, this makes far more sense to me now! Thanks again for the guidance!
