### ISSUE TITLE
Delegate and injector insertion

### ISSUE THREAD

**Issue by mattsah** [rdlowrey/auryn#148]
I was wondering what the arguments look like on a delegate callback and if it would be possible (without breaking compatibility) to send the injector into the callback.  I am guessing a more complex factory will actually run through it's own dependency injection so for example:

``` php
class Factory
{
    public function __construct(Foo $foo, Bar $bar) {
        ...
    }

    public function create()
    {

    }
}
```

If I delegate to `['Factory', 'create']` would create() be executed via `$injector->execute()` -- thereby allowing for DI on the method as well as the constructor?  **If not**, would it be possible to pass the `$injector` back into it similar to `prepare()`?  I find using the injector directly on these methods preferable because I can make dependencies with specific concrete/instantiated arguments.

If this is not possible, you could give some insight as to how to lazy instantiate dependencies of the same concrete class type?  I have two separate `Twig_Environments` with different loaders (a dependency for the `Twig_Environment`) that need to be injected into the same service.

**Comment by kelunik** [comment]
Instead of using a delegate for the class, you can instead delegate single parameters as shown in the added example.
