### ISSUE TITLE
Preparation for child classes

### ISSUE THREAD

**Issue by vlakarados** [rdlowrey/auryn#149]
I want to have an opinion on this case:
I want to `prepare()` a class in some special way that it's sub-classes would be invoked with the callback too. This might be useful to avoid specifying a long list of children (and populating along with the development, which is a hassle and often will be forgotten) and applying it one by one by `foreach`ing them.

```
<?php
require(__DIR__.'/vendor/autoload.php');

class X
{
    public $x = 123;
}

class Y extends X {}

$injector = new \Auryn\Injector;

$injector->prepare('\X', function ($object, $injector) {
    $object->x = 666;
}, true); // the third added parameter that will make all derived classes to have this callback applied.


$y = $injector->make('\Y');
echo $y->x;

// result: 123
// should be: 666
```

Same goes for `share()`. I have a bunch of Repository classes that are shared via `foreach`. When I add new ones, I have to remember to update the list as well.

Are there any downsides to this approach?

**Comment by kelunik** [comment]
> Are there any downsides to this approach?

Yes, there are. Currently `prepare` is allowed to return a new instance of that type. How should we check that `prepare('\X', ...)` still returns `Y` if we pass `Y` in? What we could do is force the same type to be returned that's put in I guess.

**Comment by vlakarados** [comment]
That sounds like a reasonable check to do. What do other users do in this case?

**Comment by Danack** [comment]
$injector->prepare('\X', ,

**Comment by Danack** [comment]
> What do other users do in this case?

Have you ever heard of the DRY principle? It stands for 'Do repeat yourself'*:

```
$x_prepare_function = function ($object, $injector) {
    $object->x = 666;
};

$injector->prepare('\X', $x_prepare_function);
$injector->prepare('\Y', $x_prepare_function);
$injector->prepare('\Z', $x_prepare_function);
```

If you have more than a reasonable amount of classes, you should either extend Auryn injector or otherwise add functionality to have app specific rules in place. Injector::make() is public, and is what is called internally - so wrapping app specific rules around that should be possible.

**Comment by garrettw** [comment]
Not to mention that adding a Boolean parameter to `prepare()` would be a clear sign of an SRP (Single Responsibility Principle) violation.

**Comment by vlakarados** [comment]
OK, let me explain my case of when I need this.

I have a bunch of repositories (DB abstraction that declares the table, some description and multiple methods like `insert()`, `delete()`, `find()`. There are _many_ of them.

For each database table I create a repository that has injection of PDO, query builder, set up some more variables.

There is no point at making multiple repositories of the same class as they are stateless, thus, I share them `$injector->share($instance);`.

@Danack this would mean, I will **have** to create a huge definition list that will prepare all repositories. What bothers me more, we have ~10 people working on this project and all of them create repositories. Keeping this definition list up-to-date will require additional directory-parsing-checking functionality that is simply there to make.

What would be the best approach here?

**Comment by Danack** [comment]
> I will have to create a huge definition list 

Can you define 'huge' please? 

> we have ~10 people working on this project and all of them create repositories.
> Keeping this definition list up-to-date will require additional directory-parsing-checking functionality

That doesn't sound like the worst thing in the world. Or you could add a tool that creates repo classes instead.

Or as I suggested, you could extend Auryn\Injector to have more specific stuff.

```
<?php
use Auryn\Injector;

class VlakaradosInjector extends Injector
{
    private $namespacePrepares;

    public function __construct(array $namespacePrepares, Reflector $reflector = null)
    {
        parent::__construct($reflector);
        $this->namespacePrepares = $namespacePrepares;
    }

    public function make($name, array $args = array())
    {
        $obj = parent::make($name, $args);
        $objNamespace = getClassNamespace($obj);

        if (array_key_exists($objNamespace, $this->namespacePrepares) === true) {
            $fn = $this->namespacePrepares[$objNamespace];
            $fn($obj, $this);
        }

        return $obj;
    }
}

$x_prepare_function = function ($object, $injector) {
    $object->x = 666;
};

$injector = new VlakaradosInjector(
   ['Vlakarados\Repository' => $x_prepare_function] 
);


```

**Comment by vlakarados** [comment]
I have had time to think and try about all the available options and factory seems to make sense in this exact case.
