### ISSUE TITLE
make()/execute() don't accept concrete classes

### ISSUE THREAD

**Issue by mattsah** [rdlowrey/auryn#159]
I could have sworn that when calling make() or execute() and passing in an array of dependencies that concrete classes would match as well as an interface, but this doesn't seem to be the case anymore?

```
class Foo {
    public function __construct(ConcreteBar $bar)
    {
        // $bar appears to be not the instance passed
    }
}

class ConcreteBar {

}

$injector->make('Foo', ['ConcreteBar' => $bar]);
```

Does this require a definition first?

**Comment by vlakarados** [comment]
You're doing it a bit wrong.

    $injector->make('Foo', [':bar' => $bar]);

is what you want, so you use the argument variable name as a key with a prepended `:`, not the class name.

**Comment by vlakarados** [comment]
Think of it this way, if a class has 2 dependencies with the same interface, they'll have the same typehint, but different argument names:

    class MyClass {
        public function __construct(SomeInterface $first, SomeInterface $second) {...}
    }

allowing you to substitute any one of those, but not both of them (which would happen in your case).

**Comment by mattsah** [comment]
I understand that aspect of it, I'm not suggesting ':bar' functionality should be removed, merely that the more common use case would seem to be wanting to inject a concrete instance for a given argument without relying on the argument name.

Part of my confusion is that I thought this did work at one point.  Maybe I'm just mistaken.

**Comment by kelunik** [comment]
See #154.
