### ISSUE TITLE
Exceptions in $injector->make can't be recovered from

### ISSUE THREAD

**Issue by Danack** [rdlowrey/auryn#169]
We have some code that tries to create an object, or fails with an exception, but then creates a defaultFoo.

```
class Foo {
    public function __construct() {
        throw new \Exception('This failed');
    }
}

$foo = null;

try {
    $injector->make(Foo::class);
}
catch (\Exception $e) {
   $foo = Foo::createDefault();
}
```

Later we try to create that object again.

```
$injector->make(Foo::class);
```

Auryn still has Foo::class listed as an inProgressMake, and so gives a cyclic dependency failure.

> Uncaught Auryn\InjectionException: Detected a cyclic dependency while provisioning Foo in /var/www/vendor/rdlowrey/auryn/lib/Injector.php on line 345

I'm just creating this issue for reference purposes, as I suspect that it's going to be a E_WONT_FIX.

**Comment by kelunik** [comment]
Should be a very simple fix putting the `unset` into a `finally` block.

**Comment by Furgas** [comment]
PR #178. I couldn't use `finally` because it's PHP 5.5 feature.

**Comment by kelunik** [comment]
PR merged, so closing.
