### ISSUE TITLE
Please add info about using @ and + to documentation

### ISSUE THREAD

**Issue by plashenkov** [rdlowrey/auryn#172]
Hello!

The source code of `Injector` class contains `A_DELEGATE` (+) and `A_DEFINE` (@). But there is no info about how to use them in documentation (README).

Could you add some (short) info about these prefixes?

**Comment by kelunik** [comment]
PRs are welcome. ;-)

**Comment by Danack** [comment]
A mere five years later, words were added in e00a69b16ff38ef6c8ee5b78242190b39552e889

Though I really doubt the use of those args in exec/make is actually 'good'.

**Comment by plashenkov** [comment]
Cool :) Thanks!
