### ISSUE TITLE
CachingReflector asks for Reflector instance but doesn't use it

### ISSUE THREAD

**Issue by Furgas** [rdlowrey/auryn#176]
The constructor of `CachingReflector` needs a `Reflector` instance, but it's not used anywhere in this class. I guess the idea for `CachingReflector` was to decorate another `Reflector` and cache its results, but it got lost somewhere in the way.

From what I see in `StandardReflector`, the `CachingReflector` could be rebuilt to act as actual decorator. What's your opinion on this?

**Comment by Furgas** [comment]
PR #177 should cover it.

**Comment by kelunik** [comment]
Merged, so closing.

**Comment by kelunik** [comment]
Thank you for your contribution!
