### ISSUE TITLE
Error thrown with message "Cannot instantiate interface Auryn\Injector"

### ISSUE THREAD

**Issue by Chamberlainfrancis** [rdlowrey/auryn#181]
I Have error in my project, everything looks fine, I seem not to understand where it it coming from, this is the error message i get,

Error thrown with message "Cannot instantiate interface Auryn\Injector"
This is my file

`

declare(strict_types = 1);

	//namespace Createspace;
	require __DIR__ . '/../vendor/autoload.php';
	
	$injector = new \Auryn\Injector;

	$injector->alias('Http\Request', 'Http\HttpRequest');
	$injector->share('Http\HttpRequest');
	$injector->define('Http\HttpRequest', [
		':get' => $_GET,
		':post' => $_POST,
		':cookies' => $_COOKIE,
		':files' => $_FILES,
		':server' => $_SERVER,
	]);

	$injector->alias('Http\Response', 'Http\HttpResponse');
	$injector->share('Http\HttpResponse');

	return $injector;`

 if someone has encountered such error, Help is needed, I appreciate

**Comment by kelunik** [comment]
`Auryn\Injector` isn't an interface, which version are you using?

**Comment by garrettw** [comment]
Yeah... @Chamberlainfrancis you would have to be using a 5+ year old version ([commit 44f7836](https://github.com/rdlowrey/auryn/tree/44f78369b929b4a1d2276cc141f7389adc8d7d13), from June 2014, at the latest) to get that error. Download a newer version of Auryn.

**Comment by kelunik** [comment]
I think this should be answered, so closing. If not, just respond.

**Comment by Chamberlainfrancis** [comment]
@garrettw I am very Grateful, everything now working as its suppose to
