### ISSUE TITLE
Future of the repository

### ISSUE THREAD

**Issue by designermonkey** [rdlowrey/auryn#192]
After reading #190 I have  question as to the future of the project and repository. Why are PRs beig directed to https://github.com/amphp/injector instead of this repository?

**Comment by garrettw** [comment]
That's the continuation of this project. I think this repo is umaintained now.

**Comment by designermonkey** [comment]
It might be a good idea to have this repo marked as abandoned in packagist then, and leave a note somewhere here to let people know. Not directing this at you personally, but at someone who maintains the repo and has access to packagist.

**Comment by designermonkey** [comment]
I've looked at the amphp repository and I can't understand how it can be considered a replacement of this package? The readme shows method usage the same as this repo, yet I can't see how as the classes and interfaces don't implement the described functionality.

Can anyone shed some light on what this is all about?

**Comment by kelunik** [comment]
@designermonkey We've planned a new major version in amphp/injector, but it's not done, yet. That's also why none of the documentation has been updated. Our focus is currently on providing new major versions working with fibers for all other libraries in the amphp organization. Compatibility fixes will still be provided in this repository, but we won't ship new features here.

The package will likely be marked as abandoned as soon as there's a stable release for amphp/injector to direct people to the new package, but we aren't there, yet.

**Comment by designermonkey** [comment]
Hi @kelunik and thanks for the update.

**Comment by designermonkey** [comment]
@martin-hughes I'm glad that someone has options, as without wanting to sound like a stuck record, I cannot understand how Amphp Injector is a continuation of the project as it is now totally different from this injector.

I have literally no idea how to use it.

**Comment by kelunik** [comment]
@designermonkey it's very much a WIP and trying new concepts, this repository is still the recommended way until we have documentation and a release. However, our main priority is still releasing Amp v3 based versions for all our packages.
