### ISSUE TITLE
Using a factory that creates objects with different constructor parameter typehints

### ISSUE THREAD

**Issue by J7mbo** [rdlowrey/Auryn#46]
I have a factory class that can instantiate two differing objects, each with different constructor parameters.

I have abstracted out an event (action) to be one of a few types. This list could be added to in the future.

    - Torrent
    - Notification

These inherit common methods from an `Action` abstract class, which implements `ActionInterface`. Hierarchy:

    interface ActionInterface { }

    abstract class Action implements ActionInterface { }

    class Torrent extends Action 
    { 
        public function __construct(TorrentDataProvider $provider, $var)
        {
            $this->provider = $provider;
            $this->var = $var;
        }
    }

    class Notification extends Action 
    {
        public function __construct(NotificationRepository $repo, $var2, $var3)
        {
            $this->repo = $repo;
            $this->var2 = $var2;
            $this->var3 = $var3;
        } 
    }

The relevant action object should only be instantiated when needed (after verification of some other stuff - userId, unique token etc). Therefore, it shall be created via an `ActionProvider` (a factory class). 

    class ActionProvider implements ActionProviderInterface
    {
        public function build($type)
        {
            switch ($type) 
            {
                // Is it a torrent?
                case (Action::TYPE_TORRENT):
                    $action = new Torrent;
                    $action->setSomeValue("a value");
                break;
                // Is it a notification?
                case (Action::TYPE_NOTIFICATION):
                    $action = new Notification;
                    $action->setAnotherValueDifferently("a value")->andAnother("-.-");
                break;
                // Or has some other bollocks been passed in?
                default:
                    throw new Exception\AreYouRetardedException("Yes");
                break;
            }
        }
    }

As you can see, the `Torrent` action object and `Notification` action object have **different constructor parameters**. They still extend the `Action` abstract class, because in the context I am using them, this makes sense.

How can I use Auryn to say:

1. Here's a factory capable of creating objects from the ActionInterface (abstract class = "Action")
2. I am now defining the Action to be created will be of type `Notification`
3. When I call `ActionFactory::build($type)`, please instantiate the right object **with all it's relevant dependencies**

**Comment by GRMule** [comment]
I *think* I ran in to this myself today, was going to create a new bug/feature request about it.

I have a database wrapper, and I want to pass in the host, user, password, etc. Those items are coming from the Configuration object. So, I set up a delegate like this for my database class:

````
	$injector->delegate('DataAccessMysql', function (Configuration $config) {
		return new DataAccessMySql(
			$config->get('database.host'),
			$config->get('database.user'),
			$config->get('database.password'),
			$config->get('database.database')
		);
	});
````

I expected my delegate to get the dependency injected, as though I had called it with execute(), but instead, it gets a string with the name of the class. Which, of course, throws an error.

**Comment by GRMule** [comment]
Gosh I hope this is the appropriate place for this :/

This is how I worked around for now:

````
	$injector->delegate('DataAccessMysql', function () use ($injector) {
		return $injector->execute(function (Configuration $config) {
			return new DataAccessMySql(
				$config->get('database.host'),
				$config->get('database.user'),
				$config->get('database.password'),
				$config->get('database.database')
			);
		});
	});
````
