### ISSUE TITLE
Doctrine EntityManager not compatible with Auryn

### ISSUE THREAD

**Issue by Danack** [rdlowrey/auryn#48]
It hides the constructor and then does magic stuff: 

https://github.com/doctrine/doctrine2/blob/626efdafd48a01cd9f54b6b94b158a5dfb4f8261/lib/Doctrine/ORM/EntityManager.php#L809

I'll look into what can be done to make it easier for Doctrinated people to use Auryn.

**Comment by J7mbo** [comment]
Thought I'd also post how I'm sharing repositories... thing is they're all being created at the start regardless of whether or not I need them so perhaps putting them in a closure or something...

        /** Register Doctrine repositories with Auryn Injector **/
        $repositoryFiles = glob(__DIR__ . "/../Model/Repository/*Repository.php");

        array_walk($repositoryFiles, function($file) use ($app, $provider) {
            /** @var EntityManager $orm */
            $orm = $app['orm.em'];

            $repositoryName = str_replace(['Repository', '.php'], '', basename($file));
            $provider->share($orm->getRepository(sprintf('\Application\Model\Entity\%s', $repositoryName)));
        });

**Comment by kelunik** [comment]
Closing, as it seems to be solved with @J7mbo's comment.
