### ISSUE TITLE
Custom definitions not consistent with other defines.

### ISSUE THREAD

**Issue by Danack** [rdlowrey/auryn#49]
These two blocks of code should produce the same object shouldn't they?

```
$injector->defineParam('em', $entityManager);
$testClass = $injector->make("InjectTest");
```

```
$testClass = $injector->make("InjectTest", [':em' => $entityManager]);
```

The second one doesn't act the same. The custom definition doesn't get passed through when making the dependencies of InjectTest, and so the error:

> 'No definition available while attempting to provision typeless non-concrete parameter em'

is generated.

**Comment by kelunik** [comment]
@Danack In that case the `make` shouldn't store the passed instance in `$shared`, it should use it only for the current make.
