### ISSUE TITLE
Configuration writer for production

### ISSUE THREAD

**Issue by ascii-soup** [rdlowrey/auryn#7]
With the new file-based configuration options becoming available, it might be nice to add a feature for development that uses the standard reflection-based auto-wiring and then writes out the equivalent configuration for increased performance in production (and for actual-dependency discovery purposes).

**Comment by Danack** [comment]
> I'll see what I can do in the next couple of days
> ...
> Lemme know if you have any other thoughts on this.

I think I'm going to close this issue before a decade has passed.
