### ISSUE TITLE
lifecycle support

### ISSUE THREAD

**Issue by staabm** [rdlowrey/Auryn#75]
I used Auryn for the first time in a project. Since I have already used the DI/IoC concept in other langues (e.g. java) the question came up if Auryn supports something like lifecycles for the objects it provides.

What I found so far is `share` which makes a object behave like a singleton.
In java you can have things like a session-scoped object, so the DI-Container will return always the same object based on the http session. So no matter when you `make` a object, you get the very same object for the current user, even across severall http requests.

There are even more scopes, so for example you can define that the DI-Container will return the very same object as long as you stay within a certain wizzard. As soon as you leave the wizzard and later on come back to it, you get a fresh copy of your required 'wizzard-scoped' object. this object is automatically destroyed when you leave the wizzard.

This are only some samples, but maybe it is something a future version of Auryn could provide?

**Comment by J7mbo** [comment]
It sounds like you need to write application-specific logic to decide when / where to share your object if you want to do that only at certain times?

**Comment by staabm** [comment]
> It sounds like you need to write application-specific logic to decide when / where to share your object if you want to do that only at certain times?

right, my app could provide those hooks/listeners, but nevertheless Auryn need to support such a scenario in the first place (so e.g. I can bin a object per context)

**Comment by rdlowrey** [comment]
I don't necessarily agree that this is something that should be supported ... If calling code knows it's current scope it's very likely you're using the injector as a service locator. In that case you're going *looking*  for specific dependencies in your code rather than asking for explicitly what you need.

Can you illustrate in code a situation where/how you'd use this functionality so I can get a little better grasp on the intent here?

**Comment by Danack** [comment]
The methods needed for managing DIC contexts are too complex to be included in this library. It would be far more appropriate to implement them in a separate library.

However if you don't want to write a separate library, you can achieve the same result by judicious use of cloning the Injector. i.e. something like:

* Bootstrap application and setup default injector information
* Route request
* $requestInjector = clone $injector;
* Setup request specific information in $requestInjector
* Dispatch request
* Process some other executable with the $injector - all information that was setup in $requestInjector will be gone.

How contexts should work is far more part of the actual application or _maybe_ framework logic, than a DIC library.

**Comment by staabm** [comment]
I am used to CDI as "Context and Depecency Injection" but since Auryn is only a DIC you are right.

**Comment by J7mbo** [comment]
Yep, it's only an *injector*. :+1:
