### ISSUE TITLE
Specifying existing instances on the fly

### ISSUE THREAD

**Issue by raulferras** [rdlowrey/auryn#78]
Docs describe it is possible to define an injection by specifingy a pre-existing instance instead of the string class name:

```
$injector->define('MyClass', [':dependency' => $dependencyInstance]);
```

However, `make` only allows to override definition by using a different class name and not a given instance:

```
$myObj = $injector->make('MyClass', ['dependency' => 'SomeImplementation']);
```

If I try to pass it an instance it throws:

```
Warning: strtolower() expects parameter 1 to be string, object given in /xxxxx/vendor/rdlowrey/auryn/lib/Provider.php on line 752
```

Is this allowed or I'm just doing it wrong?

**Comment by J7mbo** [comment]
If you `share` a pre-existing instance, then anywhere you typehint for it the shared one will be used. Is that what you're after?

I tend to share things like my DB / ORM classes in the bootstrap. Be aware that when you share them though, you have to create them. So only do this with core classes if they have a heavy footprint. Again factories can be helpful here or even delegate (but I haven't used that yet).

**Comment by raulferras** [comment]
No, I'm trying to create an object that needs a specific EventDispatcher:

    $eventDispatcher = new EventDispatcher();
    // configure the dispatcher by hooking to events.
    $kernel = $injector->make('HttpKernel:,
array('dispatcher'=>$eventDispatcher));

This resides in a closed scope an no other place in application will need
this instance of `$kernel`. Other possible HttpKernel instances may need
its own unique dependency instances so this is not a singleton-like
instance.

**Comment by raulferras** [comment]
Oh, re-reading your response I see you are refering to sharing my
`EventDispatcher`.
I don't see why I would want to share it, but it will solve the
situation.Anyway I don't think there's need to share the dispatcher
everywhere.

**Comment by J7mbo** [comment]
If you look at "Using Existing Instances in Injection Definitions" in the readme, there are two steps you do: define the dependency as your instance (don't forget the semicolon) and then make it:

$injector->define('MyClass', [':dependency' => $dependencyInstance]); 
$myObj = $injector->make('MyClass');
':dependency' is the *name*  of the dependency parameter I believe.

**Comment by raulferras** [comment]
But what if later in another place I want to instantiate a different
HttpKernel? Wouldn't it try to use that definition again?
I forgot to say I already have a definition earlier in code for HttpKernel
to resolve the interfaces it is type hinting:

    $injector->define('HttpKernel',
array('EventDispatcherInterface'=>'EventDispatcher'));

So by default auryn provides a new instance of EventDispatcher.

If I redefine it as you say, I'm overwriting this earlier definition and
subsequent instantiations will try to use the later definition. Isn't?

**Comment by J7mbo** [comment]
So I had a `Configuration` object that I wanted a different instance of in different places. Logically, I had to provide a configuration for this.

So, I created a config file that I read from. In it, I state the object as the key and the config parameters as values.

In my code, I loop through the arrays, and define the object and associated values so that each object will have its own instance of the Configuration with its own values.

In fact, I have aliases, definitions and more in a config file so I can add/remove them at will and the application picks up the change and continues.

Just an example of what I've done - perhaps that might help you? I think Auryn provides a clear or reset or similar method or you can override an object with another. Best place for this would be a factory because they can have access to the injector if needed.

**Comment by raulferras** [comment]
What if I don't know the value of those parameters in advance?

Say I got a view factory:

    class ViewFactory{
        public function __construct($viewName,$paths){
            $this->viewName = $viewName;
            $this->paths = $paths;
        }

       public function make()
       {
             $view = new View($this->viewName,$this->paths);
             return $view;
       }
}

If in my application bootstrap I do a definition like this:

    $injection->share('ViewFactory');

Later in my controllers I will call `$injection->make('ViewFactory')` to create a new view, each one obviously with different parameters. You're telling me I need to create different definitions to create different views... Why don't simply be pass those dynamic values as parameters to `make` method? Isn't this the purpose of the injector? Why limit only in definition time?

**Comment by J7mbo** [comment]
As soon as you hit your controller layer, you shouldn't need to use the injector. Why does the make method not use viewName and paths as parameters? Your current object API States that to make multiple views, you're also going to have to make multiple ViewFactories. Doesn't seem right to me...

**Comment by raulferras** [comment]
I agree with that, I'm just trying to show an example where I would need make use of that `make`/`execute` calls overwriting with instances some of their parameters, but it seems I can't hit gold...  
Maybe I'm trying to use this injector in a wrong way.

**Comment by rdlowrey** [comment]
Sorry I'm late to the party on this but it looks like a simple syntax error:

```
$myObj = $injector->make('MyClass', ['dependency' => 'SomeImplementation']);
```

^ this results in the error because you haven't prefixed the raw parameter indicator (`:`) to the dependency param name. Everything should work as expected (from the original issue report) if you change the above code to this:

```
$myObj = $injector->make('MyClass', [':dependency' => 'SomeImplementation']);
```

**Comment by Danack** [comment]
I think the being able to pass in custom params by type name as well as by parameter name, as it makes programs be more maintainable, examplé:

```
function createFoo(Bar $iAmProgrammerWhoGivesParametersWeirdNames) {
    return new Foo($iAmProgrammerWhoGivesParametersWeirdNames);
}

$injector->delegate('Foo', 'createFoo');

```


500 lines later or in a totally different file, it's easier/saner to do:
```
$customBar = new Bar(1234);
$injector->make('Foo', [Bar::class => $customBar]);
```
As that gets inspection and code refactoring support, whereas the param names don't.

Rather than:
```
$customBar = new Bar(1234);
$injector->make('Foo', [':iAmProgrammerWhoGivesParametersWeirdNames' => $customBar]);
```


Trivial PR that I forgot to do in a new branch so am waiting till the other PR gets merged: https://github.com/Danack/Auryn/commit/a3590f2f7541618f281aaa6b9d544dfa14f22a07

**Comment by Danack** [comment]
The counter argument to allowing types to be allowed in as the custom args is that it's less confusing overall. For various reasons (but [particularly this one](https://github.com/rdlowrey/Auryn/issues/49]), the instances specified as custom instances to make don't get passed to the dependencies that are required for the class being instantiated. e.g. 

```
class Foo {
    function __construct(Bar $bar) {
    }
}

class Bar{
    function __construct(Baz $baz) {
    }
}

$bazInstance = new Baz();

$injector->make('Foo', ['Baz' => $bazInstance]); //I would expect the instance would be used wherever a Baz object is required.

```

The `$bazInstance` does not get passed through to the Bar constructor. This is more surprising when the custom arg is specified by type name. When it's specified by just the parameter name, it's slightly more intuitive to me that it's just going to be used directly for the creation of the thing being requested, and not passed through to other objects.


I'm really on the fence about this; having it done by parameter name makes the parameter name be part of the signature of the function that is called to create the object which I strongly dislike, and having it be done by type name is more confusing.

**Comment by Danack** [comment]
You know, we could just remove the args from make and execute. They aren't powerful enough to cater to all needs, they're pretty confusing (particularly with regard to shared/singleton objects), and cloning the injector gives everything that you would need.

```
$injector = clone $originalInjector;
$injector->alias('Dispatcher', get_class($eventDispatcher));
$injector->share($eventDispatcher);
$kernel = $injector->make('HttpKernel');
```

All the having to think about it goes away.....

**Comment by J7mbo** [comment]
Make / execute args, unless there's an alternative for those on-the-fly args, are critical for what I use the lib for (automatic controller instantiation, injection and 'slugs' from request args).

**Comment by ascii-soup** [comment]
I'm in a similar position to @J7mbo above, being able to specify args on-the-fly is a big part of my use case for Auryn (and IMO one of its best features).

**Comment by Danack** [comment]
> and IMO one of its best features.

It's one of it's most _useful_ features.....I don't think it can be the best as it has the quite surprising and almost certainly undesired behaviour I noted above, of sometimes using the extra args, and other times just ignoring them.

I can understand why you wouldn't want it removed - but I don't think it's that difficult to reimplement in a more reasonaboutable way.

```
function makeOnTheFly(Injector $originalInjector, $type, $oneOffArgs) {
    $injector = clone $originalInjector;

    foreach ($oneOffArgs as $key => $value) {
        if(substr($key, 0, 1) === ':') {
            $paramName = substr($key, 1);
            $injector->defineParam($paramName, $value);
        }
        else if (is_object($value)) {
            $injector->alias($key, get_class($value));
            $injector->share($key, $value);
        }
        else {
            $injector->alias($key, $value);
         }
    }

    return $injector->make($type);
}
```

The only thing that this wouldn't allow is the passing of parameters by order....

**Comment by ascii-soup** [comment]
I'm a bit confused, so can I clarify something:

Are you saying that overriding parameters should (or could, rather) be done by type name in addition to parameter name, but that adding this feature would make the ability to pass in overrides confusing as they wouldn't be used throughout the dependency-resolution (as far as then creating child objects goes)?

**Comment by kelunik** [comment]
This is already possible, you just forgot the `:` for that says it's a raw value instead of a class name.

**Comment by guilhermeaiolfi** [comment]
I don't think the example covers what is being discussed here. What we want is to specify args by its class name and not args name (what your example is about). For examples:

```` 
"stdClass" => $stdClass

**Comment by kelunik** [comment]
The initial issue has been:

> However, make only allows to override definition by using a different class name and not a given instance:

A given instance is possible.

Please open another issue instead of mixing two issues.

**Comment by guilhermeaiolfi** [comment]
All right, here it is: https://github.com/rdlowrey/auryn/issues/154
