### ISSUE TITLE
"Injection definition/implementation required for non-concrete parameter" exception is a liar

### ISSUE THREAD

**Issue by PeeHaa** [rdlowrey/Auryn#79]
The exception which gets thrown when an implementation is needed is lying about the parameter name.

    interface Foo {}

    class Bar
    {
        public function __construct(Foo $foo) {}
    }

    $injector = new Provider();

    $injector->make('Bar');

results in:

> Injection definition/implementation required for non-concrete parameter **$interface** of type Foo' in 

where I would expect it to say the parameter is called `$foo`.

**Comment by rdlowrey** [comment]
Thanks for the report -- this should now be resolved in current master

**Comment by PeeHaa** [comment]
Did the public API stay the same? I.e. can I just use master and crash test dummy it in a project I currently use a "rdlowrey stable release ™"?

**Comment by rdlowrey** [comment]
It should be pretty much the same IIRC. It's not an official release yet (dev-master) but it's heading that way.
