### ISSUE TITLE
New versions?

### ISSUE THREAD

**Issue by mattsah** [rdlowrey/Auryn#90]
Any chance for a new tag soon.  It seems the last stable release was back in Oct 2014 (unless I'm missing something).  I've had some longer projects (months) which are going to be going stable soon and been using dev, but I don't want to push them to prod on dev-master, is there a roadmap for a 1.0?

**Comment by rdlowrey** [comment]
Sure, I've been pretty busy lately. Will try to do some Auryn tidying up tomorrow. Thanks for the bump :+1:

**Comment by rdlowrey** [comment]
Tagged https://github.com/rdlowrey/Auryn/releases/tag/v0.15.0 today. Thanks.
