### ISSUE TITLE
Examples showing non-existent class

### ISSUE THREAD

**Issue by GRMule** [rdlowrey/Auryn#91]
Several examples show passing a new instance of Auryn\ReflectionPool into Injector constructor. However, that class does not seem to be defined anywhere in the library.

The Injector constructor itself creates a new CachingReflector if no dependency is passed -- is the documentation out of date in this respect?

**Comment by rdlowrey** [comment]
This is addressed by https://github.com/rdlowrey/Auryn/commit/be3807b62a6991e61151b55b6974dc1289afabd5

Thanks :+1:
