### ISSUE TITLE
Provision function delegates with dependencies

### ISSUE THREAD

**Issue by GRMule** [rdlowrey/Auryn#92]
This may be a bug, or a feature request. When using a delegate function, either as a closure or a named function, I expected the delegate to be provisioned with hinted dependencies as though it were called by execute(). In actuality, it receives a string as an argument -- the name of the class being delegated.

A change to this behavior may have BC issues, if someone is using that string for a centralized provider.

Here is a repo using a closure: https://gist.github.com/GRMule/addd42fe35263b3f518a

And a similar repo, using a named function: https://gist.github.com/Danack/e54e9d9fa84914facb24

My real use-case, I have a database wrapper, and I want to pass in the host, user, password, etc. Those items are coming from a Configuration object. So, I set up a delegate like this for my database class:

    $injector->delegate('DataAccessMysql', function (Configuration $config) {
        return new DataAccessMySql(
            $config->get('database.host'),
            $config->get('database.user'),
            $config->get('database.password'),
            $config->get('database.database')
        );
    });

I expected my delegate to get the dependency injected, as though I had called it with execute(), but instead, it gets a string with the name of the class. Which, of course, throws an error.

I was able to work around the problem using this, which gives a fair idea of the *expected* behavior:

````
    $injector->delegate('DataAccessMysql', function () use ($injector) {
        return $injector->execute(function (Configuration $config) {
            return new DataAccessMySql(
                $config->get('database.host'),
                $config->get('database.user'),
                $config->get('database.password'),
                $config->get('database.database')
            );
        });
    });
````

**Comment by rdlowrey** [comment]
Could you try the current `dev-master` now that #93 is merged and let me know if you get the behavior you expect?

**Comment by GRMule** [comment]
That did the trick! Thanks!
